config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("manas_apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("finance/", include("finance.urls", namespace="finance")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

finance/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from finance.views import SearchTransactionsView

app_name='finance'
urlpatterns = [
    path("add_expense", TemplateView.as_view(template_name="expense/add_expense.html"), name="add_expense"),
    path("search_transactions", TemplateView.as_view(template_name="transactions/search_transactions.html"), name="search_transactions"),
    path("transaction_results/", SearchTransactionsView.as_view(), name="transaction_results"),
]

finance/models.py
from config.settings.base import STATICFILES_FINDERS
from django.db import models
from django.utils.timezone import now

# Create your models here.
class ExpenseType(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(max_length=256, blank=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(max_length=256, blank=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


class Expense(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(ExpenseType, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(ExpenseCategory, on_delete=models.SET_NULL, null=True)
    estimated = models.FloatField()
    actual = models.FloatField()
    date = models.DateTimeField(default=now)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name + '-' + self.type.name + '-' + self.category.name + '-' + str(self.actual)


class TransactionType(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(max_length=256, blank=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


class TransactionCategory(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(max_length=256, null=True, blank=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


class Actors(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(max_length=256, null=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    created = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name


class Transactions(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(TransactionType, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(TransactionCategory, on_delete=models.SET_NULL, null=True)
    value = models.FloatField()
    sender = models.ForeignKey(Actors, on_delete=models.SET_NULL, null=True, related_name="%(app_label)s_%(class)s_sender")
    receiver = models.ForeignKey(Actors, on_delete=models.SET_NULL, null=True, related_name="%(app_label)s_%(class)s_receiver")
    date = models.DateTimeField(default=now)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name + '-' + self.type.name + '-' + self.category.name + '-' + str(self.value)

finance/forms.py
from django.forms import ModelForm, fields
from finance.models import Expense, ExpenseCategory, ExpenseType, Transactions
from crispy_forms.helper import FormHelper
from django import forms
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Field, Div


class ExpenseForm(ModelForm):
    class Meta:
        model = Expense
        exclude = ['created', 'updated']


class ExpenseTypeForm(ModelForm):
    class Meta:
        model = ExpenseType
        exclude = ['created', 'updated']


class ExpenseCategoryForm(ModelForm):
    class Meta:
        model = ExpenseCategory
        exclude = ['created', 'updated']

finance/views.py
from finance.models import Transactions
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView
from finance.forms import ExpenseForm, ExpenseTypeForm, ExpenseCategoryForm
from django.db.models import Q

# Create your views here.
class ExpenseFormView(View):
    template_name = 'expense/add_expense.html'

    def get(self, request):

        return HttpResponse(self.template_name)


class SearchTransactionsView(ListView):
    model = Transactions
    template_name = 'transactions/search_transactions.html'
    print("here")

    # def get_queryset(self):
    #     transactions = []
    #     name = self.request.GET.get('tname', None)
    #     value = self.request.GET.get('tvalue', None)
    #     to = self.request.GET.get('tto', None)
    #     tfrom = self.request.GET.get('tfrom', None)

    #     if name:
    #         transactions = Transactions.objects.filter(Q(name__icontains=name))

    #     else:
    #         transactions = Transactions

    #     return transactions

finance/templates/transactions/search_transactions.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block title %} Search
Transactions {% endblock %} {% block content %}
<div class="container gap-3">
  <div class="p-2 row">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Search Transactions</h3>
          <h6 class="card-subtitle mb-2 text-muted">
            Use the fields to search
          </h6>
          <form class="form-inline", action="{% url 'finance:transaction_results' %}" method="GET">
            {% csrf_token %}
            <!-- {{ form|crispy }} -->
            <div class="row g-3">
              <div class="col-md-4">
                <label for="tname" class="form-label">Name</label>
                <input type="text" class="form-control" id="tname" />
              </div>
              <div class="col-md-4">
                <label for="tvalue" class="form-label">Value</label>
                <input
                  type="text"
                  class="form-control"
                  id="tvalue"
                />
              </div>
              </div>
              <div class="row g-3">
              <div class="col-md-4">
                <label for="tto" class="form-label">To</label>
                <select id="tto" class="form-select">
                  <option selected>Choose...</option>
                  <option>...</option>
                </select>
              </div>
              <div class="col-md-4">
                <label for="tfrom" class="form-label">From</label>
                <select id="tfrom" class="form-select">
                  <option selected>Choose...</option>
                  <option>...</option>
                </select>
              </div>
              <div class="col-8">
                <button type="submit" class="btn btn-outline-primary">
                  Search
                </button>
              </div>
            </div>
            <!-- <button type="submit" class="btn btn-outline-primary">Search</button> -->
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="p-2 row justify-content-center">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Results</h5>
          <h6 class="card-subtitle mb-2 text-muted">
            Trnsaction results
          </h6>
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Date</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Category</th>
                <th scope="col">Amount</th>
                <th scope="col">From</th>
                <th scope="col">To</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                <tr>
                  <th scope="row"><a href="">{{ forloop.counter }}</a></th>
                  <td>{{ transaction.transaction_date|date:"d M Y" }}</td>
                  <td>{{ transaction.name }}</td>
                  <td>{{ transaction.type }}</td>
                  <td>{{ transaction.category }}</td>
                  <td>{{ transaction.amount }}</td>
                  <td>{{ transaction.from }}</td>
                  <td>{{ transaction.to }}</td>
                  <td><a class="btn btn-danger btn-sm" href="" role="button">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}